name: CI

on:
  push:
    branches:
      - master
      - v4
  pull_request:
    branches:
      - master
      - v4

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.10"]
        include:
          - python-version: "3.8"
            requirements_file: requirements_minpandas.txt
          - python-version: "3.10"
            requirements_file: requirements_dev.txt

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'etc/${{matrix.requirements_file}}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r etc/${{matrix.requirements_file}}
        pip install -e .
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with pytest
      run: |
        pytest tests -n auto --dist loadscope
